### PR TITLE
Update structure and vinyl version 2.0.0

### PR DESCRIPTION
**Pull request by demurgos**
Hi,
This PR updates the directory structure with the latest [generator](https://github.com/typings/generator-typings) structure and adds typings for version `2.0.0` of `vinyl`.

- Drop method `pipe`
- Add property `symlink`

**This removes the test-cases**. `vinyl` changed a lot in the last weeks, and the current tests were no longer applicable (the path property was no longer set in the constructor). The generator currently supports only `blue-tape` for the tests. Is it worth converting the tests from the source to `blue-tape` or should we investigate about how to use `mocha` with the generator's structure ?

### CODE REVIEW

**Comment by blakeembrey** [comment]
Looks amazing! Thanks for your contributions 😄 /cc @felixfbecker for input.

**Comment by felixfbecker** [comment]
I would like to support version 1.x in a branch, so could you please do your project structure / styling updates into a separate PR first, and then the updates for 2.0?

As for the tests, I always found the test structure the generator generates overly complicated. For me a definition file is about syntax, not runtime, so compiling files is enough for testing. So you can keep the test structure as-is, but if you really want to do the work and change it all to runtime tests, that's okay of course too.

**Comment by demurgos** [comment]
@felixfbecker 
Ok, I'll do two PR: one for the structure and one for the version `2.0.0`.

I am also waiting for a final answer on gulpjs/vinyl#119. We are [currently declaring the  `stat` property](https://github.com/types/npm-vinyl/blob/master/index.d.ts#L69) but it is documented only as an option.

**Comment by felixfbecker** [comment]
Re `stat`: We can make it `private`.

**Comment by demurgos** [comment]
Ok, I'll try to use a union type, but if I cannot make it work, I'll simply mark it as private until it is solved (but it can break [some dependent code](https://github.com/ivogabe/gulp-typescript/blob/2d97bd72e19bcf1a0a0a898e11a0bf39721f3280/lib/types.ts#L12)).

**Comment by felixfbecker** [comment]
Actually, let's keep `stat` in here then. We have some private API in the NodeJS typings as well, the typings should only reflect what's there. It's the user's decision to use that private API or not.

**Comment by unional** [comment]
@felixfbecker we may go through this before, but testing runtime is needed, at least to ensure the API is typed correctly, please see if this would help:

https://github.com/typings/generator-typings#about-writing-tests-for-typings

**Comment by felixfbecker** [comment]
@unional Yeah I remember our argument, but compilation tests are better than no tests. Removing all tests is a no-go

**Comment by unional** [comment]
Yes, of course. The tests need to stay

**Comment by demurgos** [comment]
Yep, sorry: I was starting to convert all tests from `mocha` to `blue-tape` to run them, but @felixfbecker gave me more explanations in an other PR. I'll add the tests from the source in the next PR.

**Pull request closed without merging**
